branches:
  only:
  - master

language: node_js

sudo: false

node_js:
  - 4.4.7

before_install:
  - openssl aes-256-cbc -K $encrypted_89bd28d8dce9_key -iv $encrypted_89bd28d8dce9_iv
    -in travis-deploy.enc -out ~/.ssh/travis-deploy -d
  - chmod 600 ~/.ssh/travis-deploy
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/travis-deploy
  - cp ssh_config ~/.ssh/config
  - git config --global user.name "kyangc"
  - git config --global user.email kyangc@gmail.com
  - git clone -b master git@github.com:kyangc/Blog.git .deploy_git

install:
  - npm install hexo-cli -g
  - npm install
  - npm install hexo-generator-feed --save
  - npm install hexo-generator-sitemap --save
  - npm install hexo-deployer-git --save
  - npm install hexo-algolia --save
  - npm install hexo-util --save
  - npm install bluebird --save

script:
  - hexo clean
  - hexo g
  - hexo d
